# Generated by Django 5.1.3 on 2024-12-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='feel',
        ),
    ]
